/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SiamoNoi.FinalProject.PegawaiUser;

/**
 *
 * @author AhmadSyifaur<ahmadsyifaur11@gmail.com>
 */
public class FrameCekPembeli extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameCekPembeli
     */
    public FrameCekPembeli() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sudahButton = new javax.swing.JButton();
        belumButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Apakah Customer Sudah Pernah Melakukan Transaksi ?");

        sudahButton.setText("Sudah");
        sudahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sudahButtonActionPerformed(evt);
            }
        });

        belumButton.setText("Belum");
        belumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belumButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sudahButton)
                        .addGap(18, 18, 18)
                        .addComponent(belumButton)
                        .addGap(59, 59, 59)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sudahButton)
                    .addComponent(belumButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void belumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belumButtonActionPerformed
        // TODO add your handling code here:
        new FameInsertCustomer().setVisible(true);
    }//GEN-LAST:event_belumButtonActionPerformed

    private void sudahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sudahButtonActionPerformed
        // TODO add your handling code here:
        new TransactPgw().setVisible(true);
    }//GEN-LAST:event_sudahButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton belumButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sudahButton;
    // End of variables declaration//GEN-END:variables
}
